# Generated by Django 4.0.4 on 2022-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_createnewuserprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='createnewuserprocedure',
            name='succesful_operation',
            field=models.BooleanField(default=True),
        ),
    ]
