# Generated by Django 4.0.4 on 2022-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_createnewuserprocedure_succesful_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createnewuserprocedure',
            name='succesful_operation',
        ),
    ]
