# Generated by Django 4.0.4 on 2022-04-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_emailmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='success_message',
            new_name='message',
        ),
    ]
