# Generated by Django 4.0.4 on 2022-04-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0007_rename_success_message_emailmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
