# Generated by Django 4.0.4 on 2022-04-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0009_remove_emailmessage_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createnewuserprocedure',
            name='groups',
        ),
        migrations.AddField(
            model_name='createnewuserprocedure',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
