# Generated by Django 4.0.4 on 2022-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0013_createnewuserprocedure_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createnewuserprocedure',
            name='groups',
        ),
        migrations.AddField(
            model_name='createnewuserprocedure',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
